# Using multiple workflow .yaml files
# https://stackoverflow.com/questions/64009546/how-to-run-multiple-github-actions-workflows-from-sub-directories


# TODO
# Preventing concurrent workflows (e.g. multiple merges to master at once)
# https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
# From: https://github.community/t/how-to-limit-concurrent-workflow-runs/16844/
#
# Further split sub-directories' actions/workflows for more granular control.
#   - https://stackoverflow.com/questions/64009546/how-to-run-multiple-github-actions-workflows-from-sub-directories


# If we decide to use Docker - Using local Dockerfile in pipeline:
#   steps:
#   - name: Check out code
#     uses: actions/checkout@v3
#   - name: Build docker images
#     run: docker build -t local < .devcontainer/Dockerfile # .devcontainer is the local path
#   - name: Run tests
#     run: docker run -it -v $PWD:/srv -w/srv local make test
#  OR
#   - name: Build docker images
#     run: docker-compose build
#   - name: Run tests
#     run: docker-compose run test
# Ref: https://stackoverflow.com/questions/61154750/use-local-dockerfile-in-a-github-action


name: CD


on:
  workflow_dispatch:
    inputs:
      clientVersion:
        description: "Sets (or increments if 'true') client app version"
        required: false
        default: ""
  # Publish your release in GitHub and have your pipeline react to deploy the package
  release:
    types: [ published ]
  # Run the pipeline on merge to `master` and do the release/deploy then.
  # pull_request:
  #   types: [ closed ]
  #   branches: [ master ]
  #
  # Run on CI completion (the `if:` in the `deploy` job below would need updating accordingly)
  # workflow_run:
  #   workflows: [ 'CI' ]
  #   types: [ completed ]
  #   branches: [ master ]


defaults:
  run:
    shell: bash
    working-directory: ./


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gitUserName: ${{ github.actor }}
  gitUserEmail: ${{ github.actor }}@users.noreply.github.com
  nodeVersion: 16
  clientVersion: ""  # Can be declared via `env`, `workflow_dispatch.inputs`, or `release` -> `github.ref_name`


jobs:
  cd-client:
    runs-on: ubuntu-latest

    outputs:
      CLIENT_CACHE_ID: ${{ env.CLIENT_CACHE_ID }}

    # Only run on merge to master, but not on PR to master since PRs are just drafts, not officially prod-ready code.
    #
    # Note: At least one job in each workflow must have no dependencies, i.e. no `needs` block.
    # However, we can get around that using a conditional expression, i.e. `if` block.
    #
    # See:
    #   - https://github.community/t/depend-on-another-workflow/16311/3
    #   - https://stackoverflow.com/questions/66205887/only-run-github-actions-step-if-not-a-pull-request/66206183#66206183
    # if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && (github.event.pull_request.merged || github.event.workflow_run.conclusion == 'success') }}
    steps:
      - name: CD:Client - Checkout repository branch
        uses: actions/checkout@v3

      - name: CD:Client - Set NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}

      # Consolidate any source of the new client version into one place, `env.clientVersion`, for ease of use
      # throughout all other workflows/jobs/actions/steps.
      #
      # Since the only `release` event we listen to is `publish`, we can safely assume the ref-name is the tag name.
      #
      # See:
      #   - "Release" event and object info: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
      - name: CD:Client - Set version number
        run: |
          if [[ -n "${{ env.clientVersion }}" ]] || [[ -n "${{ inputs.clientVersion }}" ]] || [[ "$GITHUB_EVENT_NAME" == 'release' ]]; then
              if [[ "$GITHUB_EVENT_NAME" == 'release' ]]; then
                  echo "clientVersion=$GITHUB_REF_NAME" >> $GITHUB_ENV
              elif [[ -n "${{ inputs.clientVersion }}" ]]; then
                  echo "clientVersion=${{ inputs.clientVersion }}" >> $GITHUB_ENV
              fi
          fi

      # It seems strangely difficult to link different workflows together without re-running them.
      # As such, we can't just arbitrarily add a dependency on CI without making sure this CD run uses the
      # correct respective CI run.
      #
      # Thus, rather than use the `gh` API or similar to get the previous CI run, simply re-init the front-end.
      # This ensures the code used in this workflow is the correct version.
      # i.e. We might have multiple CI/CD pipelines running at once, each with a different version of the code,
      # so don't get the most up-to-date version of the code, rather get the version associated with this specific
      # run (via the `CLIENT_CACHE_ID`).
      #
      # Note that we can't use the `needs` object here since this job needs to remain dependency-free.
      - name: CD:Client CD - Init
        uses: ./.github/workflows/actions/client/init
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          gitUserName: ${{ env.gitUserName }}
          gitUserEmail: ${{ env.gitUserEmail }}
          nodeVersion: ${{ env.nodeVersion }}

      - name: CD:Client - Output cache ID
        id: cd-client-output-cache-id
        run: |
          echo "CLIENT_CACHE_ID=${{ env.CLIENT_CACHE_ID }}" >> $GITHUB_OUTPUT

      - name: CD:Client - Build - Download CI cache
        id: cd-client-build-download-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            dist
            package.json
            package-lock.json
          key: ${{ env.CLIENT_CACHE_ID }}
        continue-on-error: true

      - name: CD:Client - Build - Generate CI artifacts
        if: ${{ failure() || (steps.cd-client-build-download-cache.outputs.cache-hit != 'true') || (env.clientVersion != '') }}
        uses: ./.github/workflows/actions/client/build
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          gitUserName: ${{ env.gitUserName }}
          gitUserEmail: ${{ env.gitUserEmail }}
          nodeVersion: ${{ env.nodeVersion }}
        with:
          clientVersion: ${{ env.clientVersion }}


  cd-deploy:
    runs-on: ubuntu-latest
    needs: [ cd-client ]  # This automatically checks if `${{ needs.cd-client.result == 'success' }}` so job won't run if prev job was skipped or failed
    env:
      CLIENT_CACHE_ID: ${{ needs.cd-client.outputs.CLIENT_CACHE_ID }}
    permissions:
      pages: write      # Grant write permissions to deploy to the `gh-pages` (or whatever is specified in "Settings") branch
      id-token: write   # to verify the deployment originates from an appropriate source
      deployments: write
      packages: write
      actions: write
      contents: write
    steps:
      - name: CD:Client - Checkout repository branch
        uses: actions/checkout@v3

      - name: CD:Client - Set NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}

      - name: CD:Client - Deploy - Download CI cache
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            dist
            package.json
            package-lock.json
          key: ${{ env.CLIENT_CACHE_ID }}
        continue-on-error: false

      # TODO
      #   - Find out proper way to npm-login for publishing npm package to GitHub registry
      #   - Update .npmrc and these job steps accordingly
      # Alternative for gh-pages: A custom action provided by GitHub
      #   - https://github.com/actions/upload-pages-artifact
      #   - From: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

      # - name: CD:Client - Deploy - Upgrade app version
      #   if: ${{ (env.clientVersion != '') }}
      #   # Not necessarily required since `npm version` returns the version string (with "v" in it), but for reference:
      #   #   - Normal: npm version patch; git commit --amend -m "Patch to v$(jq -r '.version' package.json)"
      #   #   - Without git commit or tag: newAppVersion=$(npm version --no-git-tag-version patch); git commit -am "Patch to ${newAppVersion}"
      #   # Note that the git branch is defined here (unlike in composite actions) so we can run normal `git` CLI commands
      #   run: |
      #     git config --global user.name ${{ env.gitUserName }}
      #     git config --global user.email ${{ env.gitUserEmail }}
      #
      #     git pull
      #
      #     # New version is actually incremented and set within the client/build/ action
      #     # so we only need to push the change to the git repo here
      #     newAppVersion="$(jq -r '.version' package.json)"
      #
      #     git commit -am "Upgrade client version to ${newAppVersion}"
      #     git push
      #
      # # Ignore pre-/post- npm scripts via `npm run --ignore-scripts <my-script>`.
      # # This could be useful for, e.g. scripts like `deploy` since `predeploy` (`npm run build`)
      # # was already run in CI.
      # #
      # # Set `user.name` and `user.email` for ~/.gitconfig inline via the `--user` flag for `gh-pages`:
      # #   npm run --ignore-scripts deploy -- --user "${{ env.gitUserName }} <${{ env.gitUserEmail }}>"
      # - name: CD:Client - Deploy application to gh-pages
      #   # We need to either cache the build output after the version is incremented, or re-run
      #   # `npm run build` so the version is injected into the code where needed.
      #   run: |
      #     git pull
      #     git checkout gh-pages
      #
      #     ( for path in $(ls --ignore=dist --ignore=.git); do rm -rf "$path"; done; )
      #
      #     cp -R dist/* .
      #
      #     ( for path in dist/*; do git add "$(echo "$path" | sed -E 's/dist/./')"; done; )
      #
      #     rm -rf dist
      #
      #     newAppVersion="$(jq -r '.version' package.json)"
      #
      #     git commit -am "Upgrade client version to ${newAppVersion}"
      #     git push
